export const ROLES = Object.freeze({
  CONDOMINIUM_ADMIN: 'condominium_admin',
  TOWER_ADMIN: 'tower_admin',
  TOWER_TEAM: 'tower_team_member',
  COMMITTEE: 'committee',
  ACCOUNTANT: 'accountant',
  CONCIERGE: 'concierge',
  RESIDENT: 'resident'
});

export const PERMISSIONS = Object.freeze({
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DISABLE: 'users.disable',
  USERS_ASSIGN_ROLES: 'users.assign_roles',
  TOWERS_READ: 'towers.team.read',
  TOWERS_MANAGE: 'towers.team.manage',
  TOWERS_ASSIGN_ADMIN: 'towers.assign_administrator',
  DASHBOARD_ALL: 'dashboard.read_all_towers',
  DASHBOARD_ASSIGNED: 'dashboard.read_assigned_towers',
  PAYMENTS_CREATE: 'payments.create',
  PAYMENTS_VERIFY: 'payments.verify',
  PAYMENTS_REVERSE: 'payments.reverse',
  EXPENSES_ISSUE: 'expenses.issue',
  EXPENSES_CLOSE: 'expenses.close',
  FINES_CREATE: 'fines.create',
  FINES_CONFIRM: 'fines.confirm',
  FINES_VOID: 'fines.void',
  MAINTENANCE_MANAGE: 'maintenance.manage',
  MAINTENANCE_CREATE: 'maintenance.create',
  PARCELS_MANAGE: 'parcels.manage',
  DOCUMENTS_PUBLISH: 'documents.publish',
  ANNOUNCEMENTS_PUBLISH: 'announcements.publish',
  RESERVATIONS_MANAGE: 'reservations.manage',
  REPORTS_READ: 'reports.read',
  AUDIT_READ: 'audit.read'
});

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.CONDOMINIUM_ADMIN]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DISABLE,
    PERMISSIONS.USERS_ASSIGN_ROLES,
    PERMISSIONS.TOWERS_READ,
    PERMISSIONS.TOWERS_MANAGE,
    PERMISSIONS.TOWERS_ASSIGN_ADMIN,
    PERMISSIONS.DASHBOARD_ALL,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.PAYMENTS_VERIFY,
    PERMISSIONS.PAYMENTS_REVERSE,
    PERMISSIONS.EXPENSES_ISSUE,
    PERMISSIONS.EXPENSES_CLOSE,
    PERMISSIONS.FINES_CREATE,
    PERMISSIONS.FINES_CONFIRM,
    PERMISSIONS.FINES_VOID,
    PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.MAINTENANCE_CREATE,
    PERMISSIONS.PARCELS_MANAGE,
    PERMISSIONS.DOCUMENTS_PUBLISH,
    PERMISSIONS.ANNOUNCEMENTS_PUBLISH,
    PERMISSIONS.RESERVATIONS_MANAGE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.AUDIT_READ
  ],
  [ROLES.TOWER_ADMIN]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.TOWERS_READ,
    PERMISSIONS.TOWERS_MANAGE,
    PERMISSIONS.DASHBOARD_ASSIGNED,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.PAYMENTS_VERIFY,
    PERMISSIONS.FINES_CREATE,
    PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.MAINTENANCE_CREATE,
    PERMISSIONS.PARCELS_MANAGE,
    PERMISSIONS.ANNOUNCEMENTS_PUBLISH,
    PERMISSIONS.RESERVATIONS_MANAGE
  ],
  [ROLES.TOWER_TEAM]: [
    PERMISSIONS.TOWERS_READ,
    PERMISSIONS.DASHBOARD_ASSIGNED,
    PERMISSIONS.MAINTENANCE_CREATE,
    PERMISSIONS.PARCELS_MANAGE
  ],
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.DASHBOARD_ALL,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.PAYMENTS_VERIFY,
    PERMISSIONS.PAYMENTS_REVERSE,
    PERMISSIONS.EXPENSES_ISSUE,
    PERMISSIONS.EXPENSES_CLOSE,
    PERMISSIONS.REPORTS_READ
  ],
  [ROLES.CONCIERGE]: [
    PERMISSIONS.TOWERS_READ,
    PERMISSIONS.DASHBOARD_ASSIGNED,
    PERMISSIONS.PARCELS_MANAGE,
    PERMISSIONS.MAINTENANCE_CREATE
  ],
  [ROLES.COMMITTEE]: [
    PERMISSIONS.DASHBOARD_ALL,
    PERMISSIONS.REPORTS_READ
  ],
  [ROLES.RESIDENT]: [
    PERMISSIONS.DASHBOARD_ASSIGNED
  ]
});